version: "3.9"
services:
  psql-admin:
    image: dpage/pgadmin4:6
    container_name: psql-admin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:5050"
  psql:
    image: postgres:14-alpine
    container_name: psql
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - fullstack
    depends_on:
      - psql-admin
  go-api:
    container_name: go-api
    build:
     context: .
     dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
     - psql
    networks:
      - fullstack
volumes:
  data:
   driver: local
networks:
  fullstack:
    driver: bridge