POSTGRES_HOST:psql
POSTGRES_USER:postgres
POSTGRES_PASSWORD:password
POSTGRES_DB:godb
POSTGRES_PORT:5432
POSTGRES_SSLMODE:disable
POSTGRES_TIMEZONE:Turkey
PGADMIN_DEFAULT_EMAIL:admin@email.com
PGADMIN_DEFAULT_PASSWORD:admin
PGADMIN_LISTEN_PORT:5050