basePath: /api
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /v1/users:
    post:
      description: use this to inspect the headers set by the portal and received
        by the service
      produces:
      - application/json
      responses: {}
      summary: returns the HTTP headers
swagger: "2.0"
